#### Loading Dataset and perform some initial preprocessing


**Dataset Used**: CIC-IDS2017
* The CIC-IDS2017 dataset is a comprehensive collection of network traffic data that includes both benign and malicious activities. It is widely used for research in intrusion detection systems (IDS) and cybersecurity.

* The dataset contains various features extracted from network traffic, such as flow duration, total bytes, and packet counts, which can be used to train machine learning models for detecting cyber threats.

* The dataset is downloaded from Kaggle: [CIC-IDS2017 Dataset](https://www.kaggle.com/datasets/dhoogla/cicids2017)

In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("dhoogla/cicids2017")

print("Path to dataset files:", path)

C:\Users\Sangam\AppData\Roaming\Python\Python312\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Path to dataset files: C:\Users\Sangam\.cache\kagglehub\datasets\dhoogla\cicids2017\versions\3

In [2]:
import os

os.listdir(path)

['Benign-Monday-no-metadata.parquet',
 'Botnet-Friday-no-metadata.parquet',
 'Bruteforce-Tuesday-no-metadata.parquet',
 'DDoS-Friday-no-metadata.parquet',
 'DoS-Wednesday-no-metadata.parquet',
 'Infiltration-Thursday-no-metadata.parquet',
 'Portscan-Friday-no-metadata.parquet',
 'WebAttacks-Thursday-no-metadata.parquet']

In [5]:
!uv pip install pyarrow fastparquet

Using Python 3.12.13 environment at: C:\Users\Sangam\miniconda3\envs\MLProject
Resolved 10 packages in 1.86s
Downloading pyarrow (26.3MiB)
Downloading cramjam (1.6MiB)
 Downloaded cramjam
 Downloaded pyarrow
Prepared 3 packages in 6.90s
Installed 4 packages in 430ms
 + cramjam==2.11.0
 + fastparquet==2026.3.0
 + fsspec==2026.2.0
 + pyarrow==23.0.1

In [3]:
import pandas as pd 

files = os.listdir(path)

all_df = []

for file in files:
    print(f"Reading {file}...")
    df = pd.read_parquet(os.path.join(path, file))
    
    df.columns = df.columns.str.strip()
    
    all_df.append(df)

Reading Benign-Monday-no-metadata.parquet...
Reading Botnet-Friday-no-metadata.parquet...
Reading Bruteforce-Tuesday-no-metadata.parquet...
Reading DDoS-Friday-no-metadata.parquet...
Reading DoS-Wednesday-no-metadata.parquet...
Reading Infiltration-Thursday-no-metadata.parquet...
Reading Portscan-Friday-no-metadata.parquet...
Reading WebAttacks-Thursday-no-metadata.parquet...

In [4]:
all_df[0].head()

,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Fwd Packets Length Total,Bwd Packets Length Total,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,6,4,2,0,12,0,6,6,6.00000,0.000000,...,20,0.0,0.0,0,0,0.0,0.0,0,0,Benign
1,6,1,2,0,12,0,6,6,6.00000,0.000000,...,20,0.0,0.0,0,0,0.0,0.0,0,0,Benign
2,6,3,2,0,12,0,6,6,6.00000,0.000000,...,20,0.0,0.0,0,0,0.0,0.0,0,0,Benign
3,6,1,2,0,12,0,6,6,6.00000,0.000000,...,20,0.0,0.0,0,0,0.0,0.0,0,0,Benign
4,6,609,7,4,484,414,233,0,69.14286,111.967896,...,20,0.0,0.0,0,0,0.0,0.0,0,0,Benign

In [5]:
import numpy as np

full_dataset = pd.concat(all_df, ignore_index=True)

full_dataset.replace([np.inf, -np.inf], np.nan, inplace=True)
full_dataset.dropna(inplace=True)

In [10]:
full_dataset.sample(5)

,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Fwd Packets Length Total,Bwd Packets Length Total,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
1045956,17,49644,1,1,52,80,52,52,52.000000,0.000000,...,32,0.0,0.0,0,0,0.0,0.0,0,0,Benign
71462,17,5492788,6,4,222,292,41,35,37.000000,3.098387,...,20,24154.0,0.0,24154,24154,5291121.0,0.0,5291121,5291121,Benign
459490,17,66026,2,2,72,208,36,36,36.000000,0.000000,...,32,0.0,0.0,0,0,0.0,0.0,0,0,Benign
1412878,6,98538836,10,6,357,11595,357,0,35.700001,112.893311,...,32,10999.0,0.0,10999,10999,98500000.0,0.0,98500000,98500000,DoS Hulk
1707439,6,38,1,1,0,0,0,0,0.000000,0.000000,...,32,0.0,0.0,0,0,0.0,0.0,0,0,Benign

In [6]:
full_dataset.columns

Index(['Protocol', 'Flow Duration', 'Total Fwd Packets',
       'Total Backward Packets', 'Fwd Packets Length Total',
       'Bwd Packets Length Total', 'Fwd Packet Length Max',
       'Fwd Packet Length Min', 'Fwd Packet Length Mean',
       'Fwd Packet Length Std', 'Bwd Packet Length Max',
       'Bwd Packet Length Min', 'Bwd Packet Length Mean',
       'Bwd Packet Length Std', 'Flow Bytes/s', 'Flow Packets/s',
       'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min',
       'Fwd IAT Total', 'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max',
       'Fwd IAT Min', 'Bwd IAT Total', 'Bwd IAT Mean', 'Bwd IAT Std',
       'Bwd IAT Max', 'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags',
       'Fwd URG Flags', 'Bwd URG Flags', 'Fwd Header Length',
       'Bwd Header Length', 'Fwd Packets/s', 'Bwd Packets/s',
       'Packet Length Min', 'Packet Length Max', 'Packet Length Mean',
       'Packet Length Std', 'Packet Length Variance', 'FIN Flag Count',
       'SYN Flag Count', 'RST Flag Count', 'PSH Flag Count', 'ACK Flag Count',
       'URG Flag Count', 'CWE Flag Count', 'ECE Flag Count', 'Down/Up Ratio',
       'Avg Packet Size', 'Avg Fwd Segment Size', 'Avg Bwd Segment Size',
       'Fwd Avg Bytes/Bulk', 'Fwd Avg Packets/Bulk', 'Fwd Avg Bulk Rate',
       'Bwd Avg Bytes/Bulk', 'Bwd Avg Packets/Bulk', 'Bwd Avg Bulk Rate',
       'Subflow Fwd Packets', 'Subflow Fwd Bytes', 'Subflow Bwd Packets',
       'Subflow Bwd Bytes', 'Init Fwd Win Bytes', 'Init Bwd Win Bytes',
       'Fwd Act Data Packets', 'Fwd Seg Size Min', 'Active Mean', 'Active Std',
       'Active Max', 'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max',
       'Idle Min', 'Label'],
      dtype='object')

In [ ]:
full_dataset.describe()

,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Fwd Packets Length Total,Bwd Packets Length Total,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,Fwd Act Data Packets,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min
count,2.313810e+06,2.313810e+06,2.313810e+06,2.313810e+06,2.313810e+06,2.313810e+06,2.313810e+06,2.313810e+06,2.313810e+06,2.313810e+06,...,2.313810e+06,2.313810e+06,2.313810e+06,2.313810e+06,2.313810e+06,2.313810e+06,2313810.0,2.313810e+06,2.313810e+06,2.313810e+06
mean,1.050673e+01,1.807575e+07,1.108391e+01,1.255334e+01,6.664045e+02,1.976976e+04,2.506291e+02,2.142396e+01,6.880502e+01,8.299153e+01,...,6.537630e+00,-3.360480e+03,9.977085e+04,5.032398e+04,1.874053e+05,7.131980e+04,10172613.0,6.164088e+05,1.063716e+07,9.688133e+06
std,5.416040e+00,3.640823e+07,8.291879e+02,1.103179e+03,1.105009e+04,2.503141e+06,7.855073e+02,6.334192e+01,2.023045e+02,3.078815e+02,...,7.039324e+02,1.200084e+06,7.161351e+05,4.345795e+05,1.131814e+06,6.375820e+05,25771430.0,5.084448e+06,2.656441e+07,2.550670e+07
min,0.000000e+00,-1.300000e+01,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,-5.368707e+08,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00
25%,6.000000e+00,4.760000e+02,2.000000e+00,1.000000e+00,3.700000e+01,2.600000e+01,2.000000e+01,0.000000e+00,8.666667e+00,0.000000e+00,...,0.000000e+00,2.000000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00
50%,6.000000e+00,6.478300e+04,2.000000e+00,2.000000e+00,7.400000e+01,1.830000e+02,4.300000e+01,6.000000e+00,3.955556e+01,0.000000e+00,...,1.000000e+00,2.000000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00
75%,1.700000e+01,5.856948e+06,6.000000e+00,5.000000e+00,3.560000e+02,2.306000e+03,2.740000e+02,3.900000e+01,5.400000e+01,8.499406e+01,...,3.000000e+00,3.200000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00
max,1.700000e+01,1.200000e+08,2.197590e+05,2.919220e+05,1.290000e+07,6.554530e+08,2.482000e+04,2.325000e+03,5.940857e+03,7.125597e+03,...,2.135570e+05,1.380000e+02,1.100000e+08,7.420000e+07,1.100000e+08,1.100000e+08,120000000.0,7.690000e+07,1.200000e+08,1.200000e+08

In [11]:
full_dataset.to_parquet('../Dataset/dataset.parquet', engine='pyarrow', compression='snappy', index=False)